version: '3.5'
services:
  fp-import:
    image: docker.frcpnt.com/fp-dim/fp-import:latest
    environment:
      INTERNAL_TOKEN: JQnDht6Ef3zfzH7assCzdW
      HOST_DOMAIN: localhost
      CONTROLLER_SVC_NAME: dim-controller
      CONTROLLER_PORT: 8080
      MODULE_SVC_NAME: fp-import
      LOCAL_PORT: 8080
    restart: always
    volumes:
      - ${PWD}/lists:/lists
      - ${PWD}/config:/config
    networks:
      - fp-dim-controller_module-net

networks:
  fp-dim-controller_module-net:
    external: true
